image:
    file: Dockerfile
tasks:
    - init: "./assets/scripts/initial-setup.sh"
    - command: "./assets/scripts/recurring_setup.sh"

ports:
    - port: 8080
      onOpen: ignore
    - port: 10009
      onOpen: ignore
    - port: 9735
      onOpen: ignore
    - port: 8180
      onOpen: ignore
    - port: 11009
      onOpen: ignore
    - port: 9734
      onOpen: ignore
    - port: 8332
      onOpen: ignore
    - port: 18443
      onOpen: ignore
    - port: 28332
      onOpen: ignore
    - port: 28333
      onOpen: ignore

