image:
    file: Dockerfile
tasks:
    - init: "./assets/scripts/initial-setup.sh"
    - command: "./assets/scripts/recurring-setup.sh"
    - command: /workspace/bin/bitcoin-0.18.0/bin/bitcoind -datadir=/workspace/bitcoin/.bitcoin
    - command: /workspace/bin/lnd-linux-amd64-v0.7.0-beta-rc2/lnd --lnddir=/workspace/lnd/.lnd --routing.assumechanvalid 1
    - command: /workspace/bin/lnd-linux-amd64-v0.7.0-beta-rc2/lnd --lnddir=/workspace/lnd/.lnd2 --routing.assumechanvalid 1

ports:
    - port: 8080
      onOpen: ignore
    - port: 10009
      onOpen: ignore
    - port: 9735
      onOpen: ignore
    - port: 8180
      onOpen: ignore
    - port: 11009
      onOpen: ignore
    - port: 9734
      onOpen: ignore

