image:
    file: Dockerfile
tasks:
    - init: "./assets/scripts/initial-setup.sh"
      command: "./assets/scripts/recurring-setup.sh"
    - init: "code hello.py && clear"

ports:
    - port: 8080
      onOpen: ignore
    - port: 10009
      onOpen: ignore


