image:
    file: Dockerfile
tasks:
    - init: "./assets/scripts/initial-setup.sh"
    - command: "./assets/scripts/recurring-setup.sh"
    - command: bitcoind
    - command: lnd1
    - command: lnd2

ports:
    - port: 8080
      onOpen: ignore
    - port: 10009
      onOpen: ignore
    - port: 9735
      onOpen: ignore

